---
title: "Regression Plot"
subtitle: ''
author: "Humoon"
date: "`r Sys.Date()`"
output: html_document
documentclass: ctexart
classoption: hyperref,
---

```{r setup, include = FALSE}
source("./src/Rmarkdown_config.R")

## global options ===================================
knitr::opts_chunk$set(
  width = config$width,
  fig.width = config$fig.width,
  fig.asp = config$fig.asp,
  out.width = config$out.width,
  fig.align = config$fig.align,
  fig.path = config$fig.path,
  fig.show = config$fig.show,
  warn = config$warn,
  warning = config$warning,
  message = config$message,
  echo = config$echo,
  eval = config$eval,
  tidy = config$tidy,
  comment = config$comment,
  collapse = config$collapse,
  cache = config$cache,
  cache.comments = config$cache.comments,
  autodep = config$autodep
)
```

```{r, echo=FALSE}
downloadthis::download_dir(
  path = "./src",
  output_name = "Rscript",
  button_label = "Download R scripts",
  button_type = "danger",
  self_contained = FALSE
)
downloadthis::download_dir(
  path = "./data",
  output_name = "data",
  button_label = "Download data",
  button_type = "warning",
  self_contained = FALSE
)
downloadthis::download_dir(
  path = "./css",
  output_name = "css",
  button_label = "Download css",
  button_type = "success",
  self_contained = FALSE
)
downloadthis::download_file(
  path = "_output.yml",
  output_name = "_output",
  button_label = "Download config",
  button_type = "default",
  self_contained = FALSE
)
```

```{r}
# modules
source("./src/plot-element.R")
library(tidymodels)
library(reshape2) # to load tips data
```

```{r}
# data
data(tips)
set.seed(123)
tips_split <- initial_split(tips)
tips_training <- tips_split %>% training() # 训练集
tips_test <- tips_split %>% testing() # 测试集


# regression model
lm_model <- lm(tip ~ total_bill, data = tips_training)
# lm_model <- linear_reg() %>%
#   set_engine("lm") %>%
#   set_mode("regression") %>%
#   fit(tip ~ total_bill, data = tips)


# prediction
xs <- seq(min(tips$total_bill), max(tips$total_bill), length.out = 100) %>%
  data.table(total_bill = .)
ys_hat <- lm_model %>%
  predict(xs) %>%
  data.table(tip = .)
tips_prediction <- cbind(xs, ys_hat)


# plotting
p <- create_canvas(x = ~total_bill, y = ~tip) %>%
  add_markers(data = tips_training, name = "train", alpha = 0.65) %>%
  add_markers(data = tips_test, name = "test", alpha = 0.65) %>%
  add_lines(data = tips_prediction, name = "prediction", alpha = 1) %>%
  layout(
    legend = list(
      xanchor = "left", xref = "paper"
    )
  )
p

p %>% save_image(file = "../figure/regression.svg", width = 800, height = 600)
```
