---
title: "Bar Chart"
subtitle: ""
author: "Humoon"
date: "`r Sys.Date()`"
output:
  html_document:
    code_download: yes
    css: ../css/style.css
    fig_caption: yes
    theme: united
    highlight: haddock
    number_sections: no
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
      smooth_scroll: yes
documentclass: ctexart
classoption: hyperref,
---

```{r setup, include = FALSE}
source("../lib/Rmarkdown_config.R")

## global options ===================================
knitr::opts_chunk$set(
  width = config$width,
  fig.width = config$fig.width,
  fig.asp = config$fig.asp,
  out.width = config$out.width,
  fig.align = config$fig.align,
  fig.path = config$fig.path,
  fig.show = config$fig.show,
  warn = config$warn,
  warning = config$warning,
  message = config$message,
  echo = config$echo,
  eval = config$eval,
  tidy = config$tidy,
  comment = config$comment,
  collapse = config$collapse,
  cache = config$cache,
  cache.comments = config$cache.comments,
  autodep = config$autodep
)
```


```{r}
source("../lib/plot-element.R")
```

```{r}
p <- plot_ly(x = 1:10, y = 1:10) %>% add_markers()
p

plotly::save_image(p, file = "../figure/export-png.png", width = 800, height = 600)
plotly::save_image(p, file = "../figure/export-svg.svg", width = 600, height = 600)
plotly::save_image(p, file = "../figure/export-pdf.pdf")
```

